version: '3.9'

services:
  boligblik.mvc:
    image: ${DOCKER_REGISTRY-}boligblikmvc
    build:
      context: .
      dockerfile: BoligBlik.MVC/Dockerfile
    # volumes:
    #     - ./boligblik.mvc:/var/www/cshtml
    ports:
        - 5001:80
    networks:
        - boligblik   
    environment:
        #BaseAddress: "http://boligblik.webapi:5001"
        ConnectionStrings__DefaultConnection: "Data Source=sqlserver; Initial Catalog=FrontEndDb; User Id=sa; Password=BoligBlikDb!;Trust Server Certificate=True"
    depends_on: 
        - boligblik.webapi
       

  boligblik.webapi:
    image: ${DOCKER_REGISTRY-}boligblikwebapi
    build:
      context: .
      dockerfile: BoligBlik.WebAPI/Dockerfile
    ports:
        - 5002:80
    networks:
        - boligblik   
    environment:
        ConnectionStrings__DefaultConnection: "Data Source=sqlserver; Initial Catalog=BackEndDB; User Id=sa; Password=BoligBlikDb!;Trust Server Certificate=True"
    depends_on:
      - sqlserver


#https://hub.docker.com/_/microsoft-mssql-server

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BoligBlikDb!
      - MSSQL_PID=Evaluation
    networks:
        - boligblik  
    ports:
      - "1433:1433"
    # volumes:
    #   - ./sqlserver-init/init-db.sql:/init-db.sql
    #   - ./sqlserver-init/entrypoint.sh:/entrypoint.sh
    # command: ["/bin/bash", "/entrypoint.sh"]
    # healthcheck:
    #   test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P BoligBlikDb! -Q 'select 1'"]
    #   interval: 10s
    #   retries: 5
     
networks:
  boligblik:
    driver: bridge